Feature/project builds
samply/share-client pull request #11
Opened 2021-02-09 09:20 UTC by torbrenner

**What's in the PR**
* github actions for the builds of the different projects (currently samply, c4, dktk)
* new environment variables for the nNGM and DKTK
* removed hard coded urls from src/docker/samply_common_urls.xml
* Image is now based on newer tomcat image (9-jdk8-openjdk-slim) --> the image will only build for platform linux/amd64
* moved JMX Exporter and start.sh in docker container to /docker directory

**How to test manually**
* You can view the build actions on [my fork](https://github.com/torbrenner/share-client/actions?query=branch%3Afeature%2FprojectBuilds)
* The latest produced docker images are published at [Docker Hub](https://hub.docker.com/r/torbrenner/share-client) (With the merge github will push them to samply/share-client)

2021-02-10 12:28 UTC, TasDeniz requested changes
Please fix the merge conflict

2021-02-10 13:58 UTC, TasDeniz approved these changes

2021-02-16 12:43 UTC, djuarezgf requested changes

2021-02-16 12:53 UTC, djuarezgf commented on src/docker/start.sh
> +sed -i "s#{store-url}#${STORE_URL}#"                      "$file"
@alexanderkiel : Was denkst Du?

2021-02-16 13:01 UTC, torbrenner commented on src/docker/start.sh
> +sed -i "s#{store-url}#${STORE_URL}#"                      "$file"
I will create a seperate pull request for this.

2021-02-16 13:01 UTC, torbrenner commented on src/docker/start.sh
> +file=${CATALINA_HOME}/conf/${PROJECT}_common_config.xml
I will create a seperate pull request for this.

2021-02-16 13:54 UTC, djuarezgf commented
I will allow this merge after second review at 17.2.2021

2021-02-17 13:07 UTC, djuarezgf approved these changes

2021-02-17 13:48 UTC, merged