Add update button in inquiries_list.xhtml
samply/share-client pull request #169
Opened 2022-04-08 09:12 UTC by ManalJaidar

**What's in the PR**
* The Button that updates inquiries in the user interface

2022-05-19 13:02 UTC, djuarezgf commented on src/main/webapp/WEB-INF/includes/c_configuration_interfaces.xhtml
> +                <f:ajax execute="@form" listener="#{configurationBean.retune}" />
(only for selectBooleanCheckbox)

2022-05-19 13:02 UTC, djuarezgf commented on src/main/webapp/WEB-INF/includes/c_configuration_interfaces.xhtml
> +                <f:ajax execute="@form" listener="#{configurationBean.retune}" />
(not for text fields)

2022-05-20 06:52 UTC, TasDeniz requested changes

2022-05-20 06:52 UTC, TasDeniz commented on src/main/java/de/samply/share/client/control/ConfigurationBean.java
> +  public void retune(AjaxBehaviorEvent event) { // Note: the argument is optional.
please change the method name
It doesnt give any information what this method is doing

2022-05-20 11:47 UTC, TasDeniz approved these changes

2022-05-20 12:04 UTC, djuarezgf commented on src/main/webapp/WEB-INF/includes/c_configuration_interfaces.xhtml
> +                <f:ajax execute="@form" listener="#{configurationBean.retune}" />
Done

2022-05-20 12:07 UTC, merged