Feature development
samply/share-client pull request #94
Opened 2021-11-10 16:31 UTC by RadovanTomik

**What's in the PR**
* ...Added a plugin to skip checkstyle violations and modified the instructions to ease manual deployment

**How to test manually**
* ... Try the new instructions on a clean VM

2021-11-11 09:50 UTC, alexanderkiel requested changes
Please rebase onto the current develop.

2021-11-11 09:54 UTC, TasDeniz commented on pom.xml
> +  <version>7.4.0</version>
Please use a release version in the master branch. In the develop branch there is only a SNAPSHOT version allowed.

2021-11-11 15:08 UTC, RadovanTomik commented
Okay I did the rebase, could you check that I haven't broken anything?

2021-11-24 09:26 UTC, TasDeniz commented
you must resolve the pom.xml conflict

2022-01-12 13:32 UTC, alexanderkiel requested changes
Please remove the merge commit from develop into your feature branch, rebase all commits on the current develop branch and squash all commits into preferably one. Otherwise, I can't easily see what this PR is about. Also, please give the PR a clear, concise title without the start of "Feature".

2022-08-09 07:16 UTC, closed without merging